export const ADD = "ADD"
export const ADD_SUCCESS = "ADD_SUCCESS"
export const ADD_FAILURE = "ADD_FAILURE"
export const LOAD = "GET_ALL"
export const LOAD_SUCCESS = "LOAD_SUCCESS"
export const LOAD_FAILURE = "LOAD_FAILURE"
export const REMOVE = "REMOVE"
export const REMOVE_SUCCESS = "REMOVE_SUCCESS"
export const REMOVE_FAILURE = "REMOVE_FAILURE"
export const TOGGLE = "TOGGLE"
export const TOGGLE_SUCCESS = "TOGGLE_SUCCESS"
export const OGGLE_FAILURE = "TOGGLE_FAILURE"
export const UPDATE = "UPDATE"
export const UPDATE_SUCCESS = "UPDATE_SUCCESS"
export const UPDATE_FAILURE = "UPDATE_FAILURE"

