export default {
	ADD: 'ADD',
	ADD_SUCCESS: 'ADD_SUCCESS',
	ADD_FAILURE: 'ADD_FAILURE',

	LOAD: 'GET_ALL',
	LOAD_SUCCESS: 'LOAD_SUCCESS',
	LOAD_FAILURE: 'LOAD_FAILURE',

	REMOVE: 'REMOVE',
	REMOVE_SUCCESS: 'REMOVE_SUCCESS',
	REMOVE_FAILURE: 'REMOVE_FAILURE',

	TOGGLE: 'TOGGLE',
	TOGGLE_SUCCESS: 'TOGGLE_SUCCESS',
	TOGGLE_FAILURE: 'TOGGLE_FAILURE',

	UPDATE: 'UPDATE',
	UPDATE_SUCCESS: 'UPDATE_SUCCESS',
	UPDATE_FAILURE: 'UPDATE_FAILURE'
};